from app.models.anime import Anime
from app.models.anime_search import AnimeSearch
from app.models.genre import Genre
from app.models.media import Media
from app.models.media_genre import MediaGenre
from app.models.media_search import MediaSearch
from app.models.media_studio import MediaStudio
from app.models.media_unwanted import MediaUnwanted
from app.models.rating_search import RatingSearch
from app.models.ratings import Ratings
from app.models.registration_token import RegistrationToken
from app.models.studio import Studio
from app.models.tag import Tag
from app.models.user_settings import UserSettings
from app.models.users import Users
from app.models.watchlist import Watchlist
from app.models.watchlist_tag import WatchlistTag
