"""Add jobs table

Revision ID: 10860467e6f9
Revises: 3816f7e41d1b
Create Date: 2026-05-09 16:39:01.898888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10860467e6f9'
down_revision: Union[str, None] = '3816f7e41d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('kind', sa.Enum('user_scrape', 'update_sweep', 'seasonal_sweep', name='jobkind'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='jobstatus'), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('items_total', sa.Integer(), nullable=True),
    sa.Column('items_done', sa.Integer(), nullable=False),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('not_before_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index('ix_jobs_queued_by_age', 'jobs', ['created_at'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_index('ix_jobs_user_status', 'jobs', ['requested_by_user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_jobs_user_status', table_name='jobs')
    op.drop_index('ix_jobs_queued_by_age', table_name='jobs', postgresql_where=sa.text("status = 'queued'"))
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    # SQLAlchemy creates ENUMs as standalone Postgres TYPEs; autogenerate
    # leaves them behind on downgrade, which then collides on re-upgrade.
    # checkfirst=True so a re-run of the downgrade doesn't fail.
    sa.Enum(name='jobkind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='jobstatus').drop(op.get_bind(), checkfirst=True)
