"""Initial schema

Revision ID: 3816f7e41d1b
Revises: 
Create Date: 2026-04-19 09:26:01.002399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3816f7e41d1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector extension must exist before any Vector columns are created
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('mal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('name_eng', sa.String(), nullable=True),
    sa.Column('name_jap', sa.String(), nullable=True),
    sa.Column('other_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mal_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_anime_id'), 'anime', ['id'], unique=False)
    op.create_table('genre',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('genre_type', sa.Enum('Genres', 'ExplicitGenres', 'Themes', 'Demographics', name='genretype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_genre_id'), 'genre', ['id'], unique=False)
    op.create_table('media_unwanted',
    sa.Column('mal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mal_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_media_unwanted_id'), 'media_unwanted', ['id'], unique=False)
    op.create_table('studio',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_studio_id'), 'studio', ['id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('RestrictedUser', 'User', 'Admin', name='roletype'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('anime_search',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('title_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('description_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_anime_search_id'), 'anime_search', ['id'], unique=False)
    op.create_table('media',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=False),
    sa.Column('mal_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('name_eng', sa.String(), nullable=True),
    sa.Column('name_jap', sa.String(), nullable=True),
    sa.Column('other_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('media_type', sa.Enum('TV', 'TVSpecial', 'Movie', 'OVA', 'ONA', 'Special', name='mediatype'), nullable=False),
    sa.Column('relation_type', sa.Enum('Main', 'Summary', 'Crossover', 'SideStory', name='relationtype'), nullable=False),
    sa.Column('age_rating', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('original_source', sa.String(), nullable=True),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('scored_by', sa.Integer(), nullable=False),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('anime_season_name', sa.Enum('Winter', 'Spring', 'Summer', 'Fall', name='seasontype'), nullable=True),
    sa.Column('anime_season_year', sa.Integer(), nullable=True),
    sa.Column('airing_status', sa.String(), nullable=False),
    sa.Column('aired_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aired_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(anime_season_name IS NULL AND anime_season_year IS NULL) OR (anime_season_name IS NOT NULL AND anime_season_year IS NOT NULL)', name='check_season_parts_both_or_none'),
    sa.CheckConstraint('anime_season_year >= 1900 AND anime_season_year <= 2200', name='check_season_year_4_digits'),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mal_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_media_anime_id'), 'media', ['anime_id'], unique=False)
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_index('ix_media_year_season', 'media', ['anime_season_year', 'anime_season_name'], unique=False)
    op.create_table('registration_token',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('RestrictedUser', 'User', 'Admin', name='roletype'), nullable=False),
    sa.Column('was_used_for_user_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['was_used_for_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_registration_token_id'), 'registration_token', ['id'], unique=False)
    op.create_table('tag',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='unique_user_tag'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.Enum('default', 'red', 'blue', 'green', name='theme'), nullable=False),
    sa.Column('name_language', sa.Enum('english', 'japanese', 'romaji', name='namelanguage'), nullable=False),
    sa.Column('default_search_view', sa.Enum('anime', 'media', name='defaultsearchview'), nullable=False),
    sa.Column('rating_step', sa.Enum('half', 'quarter', 'tenth', 'hundredth', name='ratingstep'), nullable=False),
    sa.Column('spoiler_level', sa.Enum('off', 'blur', 'hide', name='spoilerlevel'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_table('media_genre',
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'genre_id', name='unique_media_genre'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_media_genre_id'), 'media_genre', ['id'], unique=False)
    op.create_table('media_search',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('title_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('description_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_media_search_id'), 'media_search', ['id'], unique=False)
    op.create_table('media_studio',
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('studio_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'studio_id', name='unique_media_studio'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_media_studio_id'), 'media_studio', ['id'], unique=False)
    op.create_table('ratings',
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('episodes_watched', sa.Integer(), nullable=True),
    sa.Column('dropped', sa.Boolean(), nullable=True),
    sa.Column('pace', sa.Enum('slow', 'normal', 'fast', name='pace'), nullable=True),
    sa.Column('animation_quality', sa.Enum('bad', 'normal', 'good', 'outstanding', name='animationquality'), nullable=True),
    sa.Column('has_3d_animation', sa.Enum('none', 'partial', 'full', name='threedanimation'), nullable=True),
    sa.Column('watched_format', sa.Enum('sub', 'dub', 'both', name='watchedformat'), nullable=True),
    sa.Column('fan_service', sa.Enum('none', 'rare', 'normal', 'heavy', name='fanservice'), nullable=True),
    sa.Column('dialogue_quality', sa.Enum('flat', 'normal', 'deep', name='dialoguequality'), nullable=True),
    sa.Column('character_depth', sa.Enum('flat', 'normal', 'complex', name='characterdepth'), nullable=True),
    sa.Column('ending_type', sa.Enum('open', 'closed', 'cliffhanger', name='endingtype'), nullable=True),
    sa.Column('ending_quality', sa.Enum('unsatisfying', 'satisfying', 'exceptional', 'not_applicable', name='endingquality'), nullable=True),
    sa.Column('story_quality', sa.Enum('weak', 'average', 'good', 'outstanding', name='storyquality'), nullable=True),
    sa.Column('originality', sa.Enum('conventional', 'unique', 'experimental', name='originality'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 0 AND rating <= 10', name='rating_range_check'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'media_id', name='unique_user_media_rating'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    op.create_index('ix_ratings_user_modified', 'ratings', ['user_id', sa.literal_column('modified_at DESC')], unique=False)
    op.create_table('user_visible_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'media_id', name='uq_user_visible_media')
    )
    op.create_index(op.f('ix_user_visible_media_id'), 'user_visible_media', ['id'], unique=False)
    op.create_index('ix_user_visible_media_user_id', 'user_visible_media', ['user_id'], unique=False)
    op.create_table('watchlist',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('priority >= 1 AND priority <= 3', name='priority_range_check'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'media_id', name='unique_user_media_watchlist'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_watchlist_id'), 'watchlist', ['id'], unique=False)
    op.create_table('rating_search',
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('note_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rating_id'], ['ratings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rating_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_rating_search_id'), 'rating_search', ['id'], unique=False)
    op.create_table('watchlist_tag',
    sa.Column('watchlist_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    sa.UniqueConstraint('watchlist_id', 'tag_id', name='unique_watchlist_tag')
    )
    op.create_index(op.f('ix_watchlist_tag_id'), 'watchlist_tag', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_tag_id'), table_name='watchlist_tag')
    op.drop_table('watchlist_tag')
    op.drop_index(op.f('ix_rating_search_id'), table_name='rating_search')
    op.drop_table('rating_search')
    op.drop_index(op.f('ix_watchlist_id'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index('ix_user_visible_media_user_id', table_name='user_visible_media')
    op.drop_index(op.f('ix_user_visible_media_id'), table_name='user_visible_media')
    op.drop_table('user_visible_media')
    op.drop_index('ix_ratings_user_modified', table_name='ratings')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_media_studio_id'), table_name='media_studio')
    op.drop_table('media_studio')
    op.drop_index(op.f('ix_media_search_id'), table_name='media_search')
    op.drop_table('media_search')
    op.drop_index(op.f('ix_media_genre_id'), table_name='media_genre')
    op.drop_table('media_genre')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_registration_token_id'), table_name='registration_token')
    op.drop_table('registration_token')
    op.drop_index('ix_media_year_season', table_name='media')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_index(op.f('ix_media_anime_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_anime_search_id'), table_name='anime_search')
    op.drop_table('anime_search')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_studio_id'), table_name='studio')
    op.drop_table('studio')
    op.drop_index(op.f('ix_media_unwanted_id'), table_name='media_unwanted')
    op.drop_table('media_unwanted')
    op.drop_index(op.f('ix_genre_id'), table_name='genre')
    op.drop_table('genre')
    op.drop_index(op.f('ix_anime_id'), table_name='anime')
    op.drop_table('anime')
    # ### end Alembic commands ###
