"""Add merge_candidates table

Revision ID: 3b7e62db78b6
Revises: 10860467e6f9
Create Date: 2026-05-09 21:39:59.551746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '3b7e62db78b6'
down_revision: Union[str, None] = '10860467e6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merge_candidates',
    sa.Column('anime_a_id', sa.Integer(), nullable=False),
    sa.Column('anime_b_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('detected_by', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'dismissed', 'merged', name='mergecandidatestatus'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('anime_a_id < anime_b_id', name='ck_merge_candidates_pair_ordered'),
    sa.ForeignKeyConstraint(['anime_a_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['anime_b_id'], ['anime.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_a_id', 'anime_b_id', name='uq_merge_candidates_pair'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_merge_candidates_id'), 'merge_candidates', ['id'], unique=False)
    op.create_index('ix_merge_candidates_pending', 'merge_candidates', ['created_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_merge_candidates_pending', table_name='merge_candidates', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_merge_candidates_id'), table_name='merge_candidates')
    op.drop_table('merge_candidates')
    # SQLAlchemy creates ENUMs as standalone Postgres TYPEs; autogenerate
    # leaves them behind on downgrade, which then collides on re-upgrade.
    sa.Enum(name='mergecandidatestatus').drop(op.get_bind(), checkfirst=True)
