"""Add the browse carousel definitions: carousels, filter sets and the links between them

Revision ID: 6f552c98412d
Revises: f0449ba5a7d4
Create Date: 2026-10-10 14:12:38.567230

Creates the tables empty; the boot-time seeder writes the core rows from its repo list.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f552c98412d'
down_revision: Union[str, None] = 'f0449ba5a7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('browse_carousel',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('see_all_limit', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('browse_filter_set',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('carousel_filter_set',
    sa.Column('carousel_id', sa.Integer(), nullable=False),
    sa.Column('filter_set_id', sa.Integer(), nullable=False),
    sa.Column('default_on', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carousel_id'], ['browse_carousel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filter_set_id'], ['browse_filter_set.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carousel_id', 'filter_set_id', name='uq_carousel_filter_set'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carousel_filter_set')
    op.drop_table('browse_filter_set')
    op.drop_table('browse_carousel')
    # ### end Alembic commands ###
