"""drop dead freshness and watch_event indexes

Three indexes no query has ever been able to use (v0.15.4; measured in
compound-docs/2026-08-06-performance-baseline.md against a prod dump).

The two `last_checked_at` sidecar indexes are unusable by construction, not
merely unused: `select_due_media_for_sweep`'s staleness predicate is a
`coalesce` across a joined table (not sargable) and its ORDER BY sits on the
nullable side of a LEFT JOIN. `EXPLAIN (ANALYZE, BUFFERS)` of that query is
byte-identical without them — same cost 912.03..918.71, same 621 buffers, same
Seq Scan on media + quicksort.

Size (88 + 56 + 40 kB) is not the argument. `last_checked_at` is the only
indexed MUTABLE column on either sidecar, so indexing it makes every sweep write
a non-HOT update — prod shows `n_tup_hot_upd = 0` across ~5.1k lifetime updates.
Dropping them is a write-path win the sweep pays nightly.

`ix_watch_events_watched_at` has no reader at all: `WatchEventDAO` only ever
queries by (user_id, media_id), and the time-series analysis `watched_at` exists
for isn't built. Re-add it alongside the first query that orders or ranges on it.

Revision ID: 80bdabf2d417
Revises: d9e4a1c7b3f2
Create Date: 2026-08-06 16:45:32.354591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '80bdabf2d417'
down_revision: Union[str, None] = 'd9e4a1c7b3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_anime_freshness_last_checked_at', table_name='anime_freshness')
    op.drop_index('ix_media_freshness_last_checked_at', table_name='media_freshness')
    op.drop_index('ix_watch_events_watched_at', table_name='watch_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_watch_events_watched_at', 'watch_events', ['watched_at'], unique=False)
    op.create_index('ix_media_freshness_last_checked_at', 'media_freshness', ['last_checked_at'], unique=False)
    op.create_index('ix_anime_freshness_last_checked_at', 'anime_freshness', ['last_checked_at'], unique=False)
    # ### end Alembic commands ###
