"""drop 25 PK-duplicating id indexes

`BaseModel.id` was declared `primary_key=True, index=True`, so every table
carried a second btree identical to the one the PRIMARY KEY constraint already
builds (plus `user_visible_media`, which doesn't inherit BaseModel but had
hand-copied the same line). Measured on a prod dump: **25 indexes, 5,744 kB,
26.9% of all index bytes in the database** — and pure write amplification, since
every INSERT maintained both.

Nothing can regress: an `id` lookup uses the PK's unique btree, which is
strictly better than the plain one being dropped here.

Deliberately NOT dropped — four `*_id` indexes that are on real FK columns
rather than the PK, and are load-bearing: `ix_media_anime_id`,
`ix_split_candidates_anime_id`, `ix_user_visible_media_user_id`,
`ix_jobs_parent_job_id`.

Revision ID: ab91b51de5dc
Revises: 80bdabf2d417
Create Date: 2026-08-06 16:48:48.736983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'ab91b51de5dc'
down_revision: Union[str, None] = '80bdabf2d417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_anime_id', table_name='anime')
    op.drop_index('ix_anime_completion_id', table_name='anime_completion')
    op.drop_index('ix_anime_freshness_id', table_name='anime_freshness')
    op.drop_index('ix_anime_search_id', table_name='anime_search')
    op.drop_index('ix_genre_id', table_name='genre')
    op.drop_index('ix_jobs_id', table_name='jobs')
    op.drop_index('ix_media_id', table_name='media')
    op.drop_index('ix_media_freshness_id', table_name='media_freshness')
    op.drop_index('ix_media_genre_id', table_name='media_genre')
    op.drop_index('ix_media_relation_edges_id', table_name='media_relation_edges')
    op.drop_index('ix_media_search_id', table_name='media_search')
    op.drop_index('ix_media_studio_id', table_name='media_studio')
    op.drop_index('ix_media_unwanted_id', table_name='media_unwanted')
    op.drop_index('ix_merge_candidates_id', table_name='merge_candidates')
    op.drop_index('ix_rating_search_id', table_name='rating_search')
    op.drop_index('ix_ratings_id', table_name='ratings')
    op.drop_index('ix_registration_token_id', table_name='registration_token')
    op.drop_index('ix_split_candidates_id', table_name='split_candidates')
    op.drop_index('ix_studio_id', table_name='studio')
    op.drop_index('ix_tag_id', table_name='tag')
    op.drop_index('ix_user_settings_id', table_name='user_settings')
    op.drop_index('ix_user_visible_media_id', table_name='user_visible_media')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_watch_events_id', table_name='watch_events')
    op.drop_index('ix_watchlist_id', table_name='watchlist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_watchlist_id', 'watchlist', ['id'], unique=False)
    op.create_index('ix_watch_events_id', 'watch_events', ['id'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_user_visible_media_id', 'user_visible_media', ['id'], unique=False)
    op.create_index('ix_user_settings_id', 'user_settings', ['id'], unique=False)
    op.create_index('ix_tag_id', 'tag', ['id'], unique=False)
    op.create_index('ix_studio_id', 'studio', ['id'], unique=False)
    op.create_index('ix_split_candidates_id', 'split_candidates', ['id'], unique=False)
    op.create_index('ix_registration_token_id', 'registration_token', ['id'], unique=False)
    op.create_index('ix_ratings_id', 'ratings', ['id'], unique=False)
    op.create_index('ix_rating_search_id', 'rating_search', ['id'], unique=False)
    op.create_index('ix_merge_candidates_id', 'merge_candidates', ['id'], unique=False)
    op.create_index('ix_media_unwanted_id', 'media_unwanted', ['id'], unique=False)
    op.create_index('ix_media_studio_id', 'media_studio', ['id'], unique=False)
    op.create_index('ix_media_search_id', 'media_search', ['id'], unique=False)
    op.create_index('ix_media_relation_edges_id', 'media_relation_edges', ['id'], unique=False)
    op.create_index('ix_media_genre_id', 'media_genre', ['id'], unique=False)
    op.create_index('ix_media_freshness_id', 'media_freshness', ['id'], unique=False)
    op.create_index('ix_media_id', 'media', ['id'], unique=False)
    op.create_index('ix_jobs_id', 'jobs', ['id'], unique=False)
    op.create_index('ix_genre_id', 'genre', ['id'], unique=False)
    op.create_index('ix_anime_search_id', 'anime_search', ['id'], unique=False)
    op.create_index('ix_anime_freshness_id', 'anime_freshness', ['id'], unique=False)
    op.create_index('ix_anime_completion_id', 'anime_completion', ['id'], unique=False)
    op.create_index('ix_anime_id', 'anime', ['id'], unique=False)
    # ### end Alembic commands ###
