"""Add freshness sidecar tables

Revision ID: cb6055f6a525
Revises: 3b7e62db78b6
Create Date: 2026-05-10 12:14:01.080667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'cb6055f6a525'
down_revision: Union[str, None] = '3b7e62db78b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_freshness',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stable_check_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_anime_freshness_id'), 'anime_freshness', ['id'], unique=False)
    op.create_table('media_freshness',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_media_freshness_id'), 'media_freshness', ['id'], unique=False)
    # ### end Alembic commands ###

    # Backfill: every existing anime/media gets a freshness row pointing
    # back at its own creation time so the sweep enters them at honest age,
    # not "never checked" (which would mass-include them in tier 1).
    # stable_check_count uses the column default of 0; created_at/modified_at
    # default to now() via BaseModel; uuid we generate inline (BaseModel's
    # default fires only via the ORM, not raw SQL). gen_random_uuid is
    # available natively in pg13+.
    op.execute(
        "INSERT INTO anime_freshness (anime_id, last_checked_at, uuid) "
        "SELECT id, created_at, gen_random_uuid() FROM anime"
    )
    op.execute(
        "INSERT INTO media_freshness (media_id, last_checked_at, uuid) "
        "SELECT id, created_at, gen_random_uuid() FROM media"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_freshness_id'), table_name='media_freshness')
    op.drop_table('media_freshness')
    op.drop_index(op.f('ix_anime_freshness_id'), table_name='anime_freshness')
    op.drop_table('anime_freshness')
    # ### end Alembic commands ###
