name: Lint & Format Check

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: phsar/

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install ruff

    - name: Run Ruff (lint + import order)
      run: |
        ruff check .
